version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
       POSTGRES_PASSWORD: postgres

  web:
    image: ggilperez/aplicacion:1.0
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB_NAME: postgres
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: postgres
    depends_on:
      - db
