# FROM Definir la imagen base
# RUN Definimos el comando de inicio
# CMD Similar a RUN, pero se ejecuta despues de instaciar el contenedor
# ENTRYPOINT Seleccionamos la aplicacion por defecto de la imagen
# ADD Copia archivos de la fuente (proyecto) adentro del contenedor
# ENV Define las variables de entorno