# Generated by Django 3.2.9 on 2021-12-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_birth', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
                ('income', models.IntegerField()),
            ],
        ),
    ]
